const BASE_URL = 'http://localhost:3000'
const MAX_LOAD_MESSAGE = 32
const REMAIN_SCROLL_TOP_LOAD_THERSHOULD = 700
const CHANGE_IS_TYPING_STATUS_DELAY = 250
const SEARCH_USER_TYPING_DELAY = 300

export default {
    BASE_URL,
    MAX_LOAD_MESSAGE,
    REMAIN_SCROLL_TOP_LOAD_THERSHOULD,
    CHANGE_IS_TYPING_STATUS_DELAY,
    SEARCH_USER_TYPING_DELAY
}